import { ReactNode } from "react";

export const metadata = {
  title: "Stock Dashboard",
  description: "Generated by create next app",
};

interface DashboardLayoutProps {
  children: ReactNode;
  futures: ReactNode;
  indexes: ReactNode;
  mutualFunds: ReactNode;
  watchList: ReactNode;
}

export default function DashboardLayout({
  children,
  futures,
  indexes,
  mutualFunds,
  watchList,
}: DashboardLayoutProps) {
  return (
    <>
      <>{children}</>
      <div className="flex  space-x-4 gap-10  h-screen">
        <div className="w-1/6 bg-beige-200 p-4  rounded-lg">{watchList}</div>
        <div className="w-1/6 bg-beige-200 p-4 rounded-lg">{futures}</div>
        <div className="w-1/6 bg-beige-200 p-4 rounded-lg">{indexes}</div>
        <div className="w-1/6 bg-beige-200 p-4 rounded-lg">{mutualFunds}</div>
      </div>
    </>
  );
}
